---

- name: Create Ansible local facts directory
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Add custom facts for WebLogic
  template:
    src: weblogic.fact.j2
    dest: /etc/ansible/facts.d/weblogic.fact

- name: Add NodeManager service
  template:
    src: nodemanager.service.j2
    dest: "/etc/init.d/{{nm_service_name}}"
    mode: 0755

