---

- hosts: all
  strategy: free
  gather_facts: true
  pre_tasks:
    - name: Give Permission to the installation folder
      file: 
        path: '{{ item }}'
        owner: '{{ fmw_user }}'
        group: '{{ fmw_group }}'
        state: directory
      with_items:
         - /opt
         - /webapps
         - /weblogs
         - '{{ oracle_base_path }}'
         - '{{ fmw_inventory_path }}'
         - '{{ wls_logs_dir }}'
         - '{{ wls_scripts_dir }}'
         - '{{ wls_config_dir }}'
      tags:
         - install

- hosts: managed_servers
  strategy: free
  roles:
    - { role: java, tags: 'install' }
    - { role: wls-install, tags: 'install' }

- hosts: admin_server
  roles:
    - { role: wls-admin-server-setup,  tags: 'install' }

